name: 量子密码组
url: http://qkdlab.gaokeyan.xyz

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: 教师
  - key: postdoc
    name: 博后
  - key: grad
    name: 研究生
  - key: ugrad
    name: 本科生
  - key: collab
    name: 合作者
  - key: alum
    name: 往届毕业生

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true
  people:
    output: true

# Navigation bar links.
navigation:
  - title: 主页
    link: /
  - title: 团队成员
    link: /#people
  - title: 研究项目
    link: /research.html
  - title: 发表工作
    link: /publications.html
  - title: 加入我们
    link: /joinus.html
  - title: 使用指南
    link: /help.html
  - title: 其他
    link: /others.html
